### ISSUE TITLE
Second .msi launched during install of 1.0.3

### ISSUE THREAD

**Issue by Reppinger** [zionyx/jenkins-tray#56]
Maybe this is not as scary as it looked to me, but I saw the following during install of JenkinsTray_v1.0.3:
![jenkinstrayissue](https://cloud.githubusercontent.com/assets/370324/10232230/7a66d34c-6855-11e5-97a1-6dcfc262774a.png)

I immediately cancelled as this looked like malware. The .msi did not have the same name the first time I tried it.

**Comment by zionyx** [comment]
Hi @Reppinger, the digital certificate is correct. 

I work for this company and they support me with license for DevExpress and development time for this project.

Due to Windows 8.1's blockade for unsigned applications, my company is kind enough to provide authenticode signing support to smoothen things out. See https://github.com/zionyx/jenkins-tray/issues/47

Btw, all releases are produced on build environments at work. Feel free to scan it at https://www.virustotal.com/ to boost your confidence a little.

Here's the scanned outcome: https://www.virustotal.com/en/url/4c68fe396e3cbf7028b1b4bac6073a67405a9006109c8dec5cf66ee70ac98148/analysis/1443740363/

**Comment by zionyx** [comment]
Maybe i should include the publisher information in the release notes.

**Comment by zionyx** [comment]
Btw, it is not the 2nd msi file, it prompts to confirm if you trust the publisher before proceeding with install.

**Comment by Reppinger** [comment]
Thanks. It was the first version where I noticed this. I mainly posted it so you could respond and set all of us at ease that it is not a problem.  Thanks for doing that!
